[project]
name = "dfss"
version = "1.0.3"
description = "DFSS: stable FileRecord-based schema library"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "DLEGOREAM_LAB" }
]

license = "Apache-2.0"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

keywords = [
    "schema",
    "metadata",
    "filerecord",
    "validation",
    "library"
]
